### PR TITLE
Miscellaneous minor cleanup

### PR DESCRIPTION
**Pull request by bfields**

### CODE REVIEW

**Comment by sid-kap** [comment]
Mostly lgtm! Why do you need to add fastparquet? pyarrow is faster I think

**Comment by bfields** [comment]
On Fri, Jan 27, 2023 at 12:58:15PM -0800, Sid Kapur wrote:
> Mostly lgtm! Why do you need to add fastparquet? pyarrow is faster I think

I'm not sure why I did that.  I'll experiment with a fresh repo.  Feel
free to drop this one.

**Comment by bfields** [comment]
On Fri, Jan 27, 2023 at 11:05:32PM -0500, bfields wrote:
> I'm not sure why I did that.  I'll experiment with a fresh repo.  Feel
> free to drop this one.

I doubt my patch is correct.  In any case, it's not sufficient.

I actually haven't managed to find a reproduceable way to get things
working on my Fedora 37 box.  The problems I run across are:

	The currently activated Python version 3.11.1 is not supported
	by the project (>=3.9,<3.11).

fixable by replacing "<3.11" in pyproject.toml by "<4";

$ poetry run build_data --data-repo-path ../../housing-data-data
...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/bfields/local/TMP/housing-data/python/housing_data/build_data.py", line 32, in main
    states_df = load_states(data_repo_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bfields/local/TMP/housing-data/python/housing_data/build_states.py", line 35, in load_states
    states_df.to_parquet(PUBLIC_DIR / "states_annual.parquet")
  File "/home/bfields/.cache/pypoetry/virtualenvs/housing-data-W_JESmi5-py3.11/lib64/python3.11/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/bfields/.cache/pypoetry/virtualenvs/housing-data-W_JESmi5-py3.11/lib64/python3.11/site-packages/pandas/core/frame.py", line 2976, in to_parquet
    return to_parquet(
           ^^^^^^^^^^^
  File "/home/bfields/.cache/pypoetry/virtualenvs/housing-data-W_JESmi5-py3.11/lib64/python3.11/site-packages/pandas/io/parquet.py", line 426, in to_parquet
    impl = get_engine(engine)
           ^^^^^^^^^^^^^^^^^^
  File "/home/bfields/.cache/pypoetry/virtualenvs/housing-data-W_JESmi5-py3.11/lib64/python3.11/site-packages/pandas/io/parquet.py", line 52, in get_engine
    raise ImportError(
ImportError: Unable to find a usable engine; tried using: 'pyarrow', 'fastparquet'.
A suitable version of pyarrow or fastparquet is required for parquet support.
Trying to import the above resulted in these errors:
 - No module named 'pyarrow._parquet'
 - Missing optional dependency 'fastparquet'. fastparquet is required for parquet support. Use pip or conda to install fastparquet.

although pyarrow is already installed; and

$ poetry run build_data --data-repo-path ../../housing-data-data
...
Final fraction of rows with population: 90.0%
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/bfields/local/TMP/housing-data/python/housing_data/build_data.py", line 44, in main
    metros_df = load_metros(counties_df)
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bfields/local/TMP/housing-data/python/housing_data/build_metros.py", line 152, in load_metros
    metros_df.to_parquet(PUBLIC_DIR / "metros_annual.parquet")
  File "/home/bfields/.cache/pypoetry/virtualenvs/housing-data-W_JESmi5-py3.11/lib64/python3.11/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/bfields/.cache/pypoetry/virtualenvs/housing-data-W_JESmi5-py3.11/lib64/python3.11/site-packages/pandas/core/frame.py", line 2976, in to_parquet
    return to_parquet(
           ^^^^^^^^^^^
  File "/home/bfields/.cache/pypoetry/virtualenvs/housing-data-W_JESmi5-py3.11/lib64/python3.11/site-packages/pandas/io/parquet.py", line 430, in to_parquet
    impl.write(
  File "/home/bfields/.cache/pypoetry/virtualenvs/housing-data-W_JESmi5-py3.11/lib64/python3.11/site-packages/pandas/io/parquet.py", line 312, in write
    self.api.write(
  File "/home/bfields/.cache/pypoetry/virtualenvs/housing-data-W_JESmi5-py3.11/lib64/python3.11/site-packages/fastparquet/writer.py", line 1291, in write
    fmd = make_metadata(data, has_nulls=has_nulls, ignore_columns=ignore,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bfields/.cache/pypoetry/virtualenvs/housing-data-W_JESmi5-py3.11/lib64/python3.11/site-packages/fastparquet/writer.py", line 895, in make_metadata
    se, type = find_type(data[column], fixed_text=fixed,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bfields/.cache/pypoetry/virtualenvs/housing-data-W_JESmi5-py3.11/lib64/python3.11/site-packages/fastparquet/writer.py", line 126, in find_type
    object_encoding = infer_object_encoding(data)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bfields/.cache/pypoetry/virtualenvs/housing-data-W_JESmi5-py3.11/lib64/python3.11/site-packages/fastparquet/writer.py", line 343, in infer_object_encoding
    if pd.isna(i):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Some combination of installing fastparquet and "poetry update" seems to
eventually get me there but I'm not quite sure what's going on.

**Comment by sid-kap** [comment]
Using fastparquet locally is totally fine, I just don't want to make the change on main

**Comment by bfields** [comment]
On Thu, Feb 02, 2023 at 01:07:06PM -0800, Sid Kapur wrote:
> Using fastparquet locally is totally fine, I just don't want to make the change on main

Makes sense.

And I overlooked the obvious, that I can avoid all my problems by
installing python 3.10 (Fedora even provides packages that that don't
conflict with the default 3.11).  So all I really need is a "dnf install
python3.10" and a "poetry install", and poetry takes care of the rest.
Figuring out why it's failing on 3.11 is a problem for another day.

**Pull request closed without merging**
